test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.with_sftp = "1"
    args.with_mysql = "1"
	args.phpversion = "8.0"

[80_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "8.0"

[none_test]

    only = ["install.subdir", "backup_restore", "upgrade" ]
    args.phpversion = "none"
